name: Build Dist Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Artifact Dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploybranch:
    name: Deploy to Dist Branch
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
        #   upload to artifact to dist branch
      - name: Upload to Dist Branch
        uses: actions/checkout@v2
        with:
          ref: dist
      - name: Deploy
        run: |
          git config --global user.email "gorbadil@gmail.com"
          git config --global user.name "gorbadil"
          git add .
          git commit -m "Deploy to dist branch"
          git push origin dist
