name: Try To Connect

on:
  # push:
  # branches:
  # - main
  workflow_dispatch:

jobs:
  uploadToVPS:
    name: Upload to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Unzip Artifact
        run: |
          unzip dist.zip
          rm dist.zip
          ls -la
      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          # script: |
          #   scp -r dist/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.SSH_PATH }}
          script: |
            echo "Hello World"
