name: Try To Connect

on:
  # push:
  # branches:
  # - main
  workflow_dispatch:

jobs:
  uploadToVPS:
    name: Upload to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          # script: |
          #   scp -r dist ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.SSH_PATH }}
          script: |
            whoami
            ls -la
